name: canary_build
on: push

env:
  CI: true
  BROCCOLI_ENV: test
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        always-auth: true
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: list versions
      run: |
        node --version
        npm --version
        yarn --version
    - name: install dependencies
      run: | 
        export PATH=$PATH:node_modules/.bin
        yarn
    - name: test
      run: |
        export PATH=$PATH:node_modules/.bin
        ember try:each
    # - name: release
    #   uses: justincy/github-action-npm-release@2.0.2
    #   id: release
    # - name: print release output
    #   if: ${{ steps.release.outputs.released == 'true' }}
    #   run: echo Release ID ${{ steps.release.outputs.release_id }}
    # - name: publish package
    #   if: ${{ steps.release.outputs.released == 'true' }}
    #   env:
    #     NPM_AUTH_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
    #   run: |
    #     yarn publish
